server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/,classpath:config/bff,classpath:config/core
        encrypt:
          enabled: false

#encrypt:
#  key: configsymmetrickey

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.tianyalan: INFO

