server:
  port: 8081

spring:
  application:
    name: core # 注册中心显示名称
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
